--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ahorcado-reactjs
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: ahorcado-reactjs
  template: 
    metadata: 
      labels: 
        app: ahorcado-reactjs
    spec: 
      containers: 
        - 
          image: docker.io/xtsofka/ahorcado-reactjs
          name: ahorcado-reactjs
          ports: 
            - 
              containerPort: 80

--- 
apiVersion: v1
kind: Service
metadata: 
  name: load-balancer
  labels: 
    app: ahorcado-reactjs
spec: 
  type: LoadBalancer
  ports: 
    - port: 80
      nodePort: 31000
      protocol: TCP
      targetPort: 80
  selector: 
    app: ahorcado-reactjs

